name: Metrics
on:
  # Schedule updates (once a day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual refresh
  workflow_dispatch:
  # Run on every push to main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_README_TOKEN }}

          # Options
          user: dozeype
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Singapore
