name: Metrics
on:
  # Schedule updates (once a day at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual refresh
  workflow_dispatch:
  # Run on every push to main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_README_TOKEN }}
          template: classic
          base: header, community, repositories, metadata
          
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_achievements: yes
          plugin_achievements_threshold: B
